import * as Things from "./things"; type ElementData = [Things.ThingID, number]; const data : ElementData[] = [ ['hydrogen', 0],
    ['helium', 4],
    ['lithium', 7],
    ['beryllium', 9],
    ['', 0],
    ['carbon', 12],
    ['nitrogen', 14],
    ['oxygen', 16],
    ['', 0],
    ['', 0],
    ['', 0],
    ['magnesium', 24],
    ['', 0],
    ['silicon', 28],
    ['phosphorus', 31],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['calcium', 40],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['iron', 56],
    ['', 0],
    ['nickel', 58],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0],
    ['', 0]
];

/**
 * Adds atoms for all relevant elements to the thing directory
 */
export function createAtoms(thingDirectory : Things.ThingDirectory) : void {
    let atomicNumber : number = 1;
    data.forEach((elementData : ElementData) : void => {
        let elementName : string = elementData[0];
        let atomicWeight : number = elementData[1];

        thingDirectory[elementName] = {
            children: {
                proton: {
                    range: [atomicNumber, atomicNumber]
                },
                electron: {
                    range: [atomicNumber, atomicNumber]
                },
                neutron: {
                    range: [atomicWeight - atomicNumber, atomicWeight - atomicNumber]
                }
            },
            imagePath: 'atom.png'
        };

        atomicNumber++;
    });
}